# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name UGridAndPoints
#' @title Represents a grid of tree loaded from XYZ file
#' @description Most important method is CalculateFeaturesR
#' @field new Constructor \itemize{
#' \item FileNamePath: path to the XYZ file
#' \item swapYZ: TRUE/FALSE
#' \item cellSize: Size of the cell
#' }
#' @field CalculateFeaturesR Calculates features by using symmetry measure
#' @field ReadFileToGridR Reads the tree from XYZ file
#' @field GetPointsR Gets a list of all points of the XYZ file
NULL

